### ISSUE TITLE
NaN price and weight 

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#10]
![fountainjs - google chrome_001](https://cloud.githubusercontent.com/assets/18617219/16649832/7a59c498-4443-11e6-8cf0-fa4f10933efa.png)
This happen after selection "Small" size for any product. The problem in our database, now we process only "Medium" and "Big" sizes.

**Comment by dezoxel** [comment]
Fixed, @Kostya47 please test

**Comment by Kostya47** [comment]
@dezoxel It is necessary to remove "Small" size for all dishes. 
![fountainjs - google chrome_003](https://cloud.githubusercontent.com/assets/18617219/16735835/36c4612c-4793-11e6-8374-19302a283d2b.png)

**Comment by dezoxel** [comment]
@Kostya47, it was not deployed to prod. Fixed it. Please test again

**Comment by Kostya47** [comment]
Verified.
