### ISSUE TITLE
Incorrect price is shown when come back from custom menu

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#103]
**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. On any day-menu set big size.
3. Press "Create own" button.
4. And back by pressing "Return prepared" button.

**AR:**
![- google chrome_010](https://cloud.githubusercontent.com/assets/18617219/17411288/6faa5a28-5a80-11e6-836f-cd34daaaeb0f.png)
**ER:**
![- google chrome_012](https://cloud.githubusercontent.com/assets/18617219/17411345/cebd9d9a-5a80-11e6-91b8-12818f7f898f.png)

**Comment by dezoxel** [comment]
Fixed. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
