### ISSUE TITLE
Need to make sorting by date for orders in basket

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#112]
Now the orders are sorted same as by adding to basket.
![- google chrome_002](https://cloud.githubusercontent.com/assets/18617219/17438590/4a77d2e2-5b2c-11e6-8cb5-1fe731e6227e.png)
It's not good, because the user can add orders randomly and then in the basket may be some confusion.

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
