### ISSUE TITLE
Active "Place order" button when "Name" field is empty

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#117]
**Preconditions:**
"Name" field must be filled from local storage

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.
4. Clear "Name" field and don't change focus.

**AR:** "Place order" button is active.
**ER:** Button must be inactive.

**Comment by dezoxel** [comment]
Can't repro. @Kostya47 please verify issue is gone

**Comment by Kostya47** [comment]
No longer relevant. Closed.
