### ISSUE TITLE
Inactive "Place order" button when "Name" field is filled

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#118]
**Preconditions:**
Local storage must be clean.

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.
4. At first select floor.
5. Than fill in name and don't change focus.

**AR:** "Place order" button is inactive.
**ER:** Button must be active.

**Comment by dezoxel** [comment]
Can't repro. @Kostya47 please verify issue is gone

**Comment by Kostya47** [comment]
No longer relevant. Closed.
