### ISSUE TITLE
[Week Switcher] Add tabs instead of radio button

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/fe#12]
For example, when i want to order on thursday only, it is not comfortable to uncheck each checkbox near dish name

**Comment by dezoxel** [comment]
Lets postpone this till our next brain storm session of the week-menu UI

**Comment by dezoxel** [comment]
Not relevant task anymore. Lets rename

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
