### ISSUE TITLE
Unable to place order error

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#121]
**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.
4. Press "Place order" button.

**AR:**
![- google chrome_006](https://cloud.githubusercontent.com/assets/18617219/17490463/8e9ede94-5dab-11e6-8f6e-8cd0a342150f.png)

**ER:** Order must be placed.

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
