### ISSUE TITLE
Active switches when custom order was added to basket

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#131]
**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. For any menu press "Create own" button.
3. Select at least one product.
4. Press "Take own" button.

**AR:** Switches are visible and active.
**ER:** Switches must not be visible.

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
