### ISSUE TITLE
Wrong position of information message about placed order

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#134]
**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.
4. Press "Place order".

**AR:**
![screenshot from 2016-08-11 11-35-07](https://cloud.githubusercontent.com/assets/18617219/17583085/e60d6d18-5fb7-11e6-8279-2850e8769ccc.png)
**ER:** Message must be at the bottom of the page.

**Comment by dezoxel** [comment]
Now it should be fixed because payment page is shown instead of week menu. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
