### ISSUE TITLE
No total price in basket

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#158]
**Preconditions:** Basket must be empty.

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add two or more products.
3. Go to basket.

**AR:** No display total price.
**ER:** Total price must be displayed.

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
