### ISSUE TITLE
Impossible to place order

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#16]
**Steps to reproduce:**
1. Go to [http://cogniance.lunches.com.ua/](url)
2. Choose and add to basket at least 1 product item
3. Click "To basket" button
4. Click "Place order"

**AR:** Order was not added and no visual actions.
**ER:** Order was added and show successful message.

**Comment by dezoxel** [comment]
It should be already fixed as a part of https://github.com/lunches-platform/fe/issues/29

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
