### ISSUE TITLE
Impossible to place order for new user

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#164]
**Preconditions:**
An existing username and address must be saved in local storage and displayed in basket.

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product to basket
3. Go to basket.
4. Clear name field.
5. Enter new username.
6. Press "Place order".

**AR:** Error! Unable to place order.
**ER:** Order must be placed.

**Comment by dezoxel** [comment]
Looks like API issue:
Create new user:

```
POST /users HTTP/1.1
Host: api.qa.lunches.com.ua
{"username":"Dez Oxel","address":"Cogniance, Okhtyrskyi Lane, 7, 2"}
```

```
{"id":"72e23f0b-edbb-471a-bc94-85f2d6f80588","clientId":1002,"fullname":"Dez Oxel","address":"Cogniance, Okhtyrskyi Lane, 7, 2","balance":0}
```

Place order:

```
POST /orders HTTP/1.1
Host: api.qa.lunches.com.ua
{"items":[{"productId":40,"size":"medium","quantity":1},{"productId":27,"size":"medium","quantity":1},{"productId":23,"size":"medium","quantity":1}],"userId":"72e23f0b-edbb-471a-bc94-85f2d6f80588","shipmentDate":"2016-08-19"}
```

```
{"errMsg":"Server error"}
```

**Comment by dezoxel** [comment]
@warlock39 please review. Create own ticket in API repo if needed. @Kostya47 please track fixing API issue. Assign back to me if needed.

**Comment by warlock39** [comment]
@Kostya47 , @dezoxel , fixed. Deploy bug

**Comment by Kostya47** [comment]
Verified.

**Comment by dezoxel** [comment]
@Kostya47 should be fixed already. Please test

**Comment by Kostya47** [comment]
Verified.
