### ISSUE TITLE
UX - Couldn't figure out how to make an order

### ISSUE THREAD

**Issue by gornostal** [lunches-platform/fe#179]
1. Натиснув "Собрать Свой"
2. Обрав складові

Що далі?

**Comment by dezoxel** [comment]
The website order flow a bit changed against google spreadsheet flow. Now you have to make confirmation of your choice by pressing "Беру свой" button and going to basket. "Беру свой" has primary color, it is designed to attract much more attention than other UI elements.

@gornostal Do you have any ideas of how to do it better?

**Comment by dezoxel** [comment]
Fixed as a part of https://github.com/lunches-platform/fe/issues/11
