### ISSUE TITLE
UX - User has to scroll too much on desktop because of huuuuge photos of food

### ISSUE THREAD

**Issue by gornostal** [lunches-platform/fe#180]
Root cause: Desktop and Mobile version cannot be the same.
Sandwich menu, full-width content only look good on mobile, IMO.

**Comment by dezoxel** [comment]
@gornostal Desktop UI is not ready, it was covered by introduction letter. Desktop has completely another approach on building UIs, we will not reuse mobile's blocks placement, alignment, etc. Just wait a bit, we will introduce it soon :)

**Comment by dezoxel** [comment]
Part of https://github.com/lunches-platform/fe/issues/126.

**Comment by dezoxel** [comment]
Fixed as a part of https://github.com/lunches-platform/fe/issues/11
