### ISSUE TITLE
Radio buttons have different color in size selector

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#185]
@Kostya47 please confirm and update description

**Comment by Kostya47** [comment]
![- google chrome_018](https://cloud.githubusercontent.com/assets/18617219/18269833/9ab3bd92-7432-11e6-9a7c-896b3d42b3ac.png)
![- google chrome_019](https://cloud.githubusercontent.com/assets/18617219/18269836/9d12c0ec-7432-11e6-9d1d-841ade7f4c57.png)
