### ISSUE TITLE
Incorrect sequence loading of page elements

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#20]
**Steps to reproduce:**
1. Go to [http://cogniance.lunches.com.ua/](url)
2. Refresh page (for repeating of the bug)
![scrn_rec-2016-07-08_13 46 18](https://cloud.githubusercontent.com/assets/18617219/16686470/12a1a202-451b-11e6-926b-2883c89f9971.gif)

**AR:** To basket button displayed at the top of the page before loading other elements.
**ER:** The button should be loaded together with the other elements and displayed at the bottom of the page.

**Comment by dezoxel** [comment]
Fixed: https://github.com/lunches-platform/fe/pull/37

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Nice! Closed.
