### ISSUE TITLE
Make toolbar fixed

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#218]

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.

**Comment by warlock39** [comment]
@Kostya47 , have you tested at iOS device? Toolbar covers week selector.
![img_5676](https://cloud.githubusercontent.com/assets/490549/18032637/72181dcc-6d13-11e6-865f-065e233baa92.jpg)

**Comment by Kostya47** [comment]
@warlock39 I confirm that this problem is present, thanks. 
@dezoxel Please fix.

**Comment by dezoxel** [comment]
Fixed as a part of https://github.com/lunches-platform/fe/issues/11
