### ISSUE TITLE
Incorrect name of page title

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#22]
**Steps to reproduce:**
1. Go to [http://cogniance.lunches.com.ua/](http://cogniance.lunches.com.ua/)

**AR:** Name title is "FountainJS".
**ER:** Заказать обеды с "date" по "date".

**Comment by dezoxel** [comment]
Done: https://github.com/lunches-platform/fe/pull/36

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
