### ISSUE TITLE
Goes to the payment page when the order was not placed

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#237]
**Preconditions:** Placing order should not work.

**Steps to reproduce:**
1. Open main page.
2. Add at least one product.
3. Go to basket.
4. Fill all required fields.
5. Press "Place order".

**AR:** After unable to place order, site switches to payment page.
**ER:** After an unsuccessful order placement site should remain on basket page.

**Comment by dezoxel** [comment]
Already fixed as a part of another task
