### ISSUE TITLE
My orders read only mode

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#25]

**Comment by warlock39** [comment]
There are some requirements for this page:
- Order is assigned to date.
- Order doesn't have status for now. 
- Order can be rejected by customer before order shipment date. 
- Order can be edited by customer before shipment date. 
- Order can't be paid. Instead, customer have account balance. Customer should add credits to his account. 

It covers not only read only mode, but any way can be useful to plan technical tasks.

**Comment by dezoxel** [comment]
Requirements by @Kostya47:
- My-orders page display orders by customer
- Order contains image, product names, price and date
- Orders are grouped by week
- Date selector is used for choosing date range
- By default orders are shows for these dates: last week, current week, next week
- Orders are sorted by date (older first)
- Toolbar has my-orders icon that leads to My Orders page
- All orders have a payment status Paid/Not paid
- All orders have a product status (???)
- Order can be inline edited
- Order can be canceled
- Edit should be disabled when shipmentDate comes
- Cancel order should be disabled when shipmentDate comes
- Show informational message (tooltip or other similar) explaining why it is not possible to edit order
- Show informational message (tooltip or other similar) explaining why it is not possible to cancel order

**Comment by dezoxel** [comment]
Skeleton completed. Remaining tasks were moved to separate tickets. @Kostya47 please test

**Comment by Kostya47** [comment]
Waiting for back-end update

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
