### ISSUE TITLE
Show next menu when friday

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#26]

**Comment by dezoxel** [comment]
Done, @Kostya47 please test

**Comment by Kostya47** [comment]
At the moment, I can't test it. 
Reasons of blocking:
    - Fake current week menu (non critical)
    - No next week menu in DB (it is my task)
    - Now is Wednesday and we have two options:
        - Falsely change date on Friday
        - Complete previous items and test it on Friday in vivo

**Comment by warlock39** [comment]
@Kostya47 , to speed up testing process of project in general, it is better to test it on Friday, @dezoxel what do you think?

**Comment by dezoxel** [comment]
@Kostya47 @warlock39 agree

**Comment by dezoxel** [comment]
@Kostya47 I have integrated new API endpoint for getting two weeks menu. Fake API has been disabled, now UI works with real API. https://github.com/lunches-platform/fe/issues/26. I believe you can test it when next week menu is ready.

**Comment by Kostya47** [comment]
Verified.
