### ISSUE TITLE
Incorrect price when "order more"

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#34]
**Steps to reproduce:**
1. Go to week menu page.
2. Set and add to basket any products.
3. In opened day menu placeholder press "order more" button.
4. Set and add to basket any products again.
5. Go to basket.

_Example:_
![fountainjs - google chrome_001](https://cloud.githubusercontent.com/assets/18617219/17016568/5e24f9d2-4f38-11e6-99fb-07b800f4cc16.png)
![fountainjs - google chrome_002](https://cloud.githubusercontent.com/assets/18617219/17016575/662e16ea-4f38-11e6-93e8-67bedd7c667f.png)
![fountainjs - google chrome_003](https://cloud.githubusercontent.com/assets/18617219/17016758/270ff400-4f39-11e6-8805-d9a47ad18714.png)

**AR:** Price = 80
**ER:** Price = **60**

**Comment by dezoxel** [comment]
It should be fixed already as a part of https://github.com/lunches-platform/fe/issues/13

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
