### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#41]
Requirements:
- my-orders icon
- basket icon
- Balance number
- User name

**Comment by dezoxel** [comment]
Done, @Kostya47 please test

**Comment by dezoxel** [comment]
Some notes:
- My Orders icon is added but for now is hidden since My Orders is not implemented yet
- Not sure that we have to add user name. I don't see such UX on any popular mobile apps and websites so I decided to skip it
- Balance number is not available yet

**Comment by Kostya47** [comment]
Verified.
