### ISSUE TITLE
Incorrect title name when change on next week

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#42]
**Steps to reproduce:**
1. Go to week menu page.
2. Switch to next week menu.

**AR:** Title name is "Меню на текущую неделю"
**ER:** Title name is "Меню на следующую неделю"

**Comment by dezoxel** [comment]
Fixed as a part of https://github.com/lunches-platform/fe/pull/43. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
