### ISSUE TITLE
Update typings to the latest version

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#44]

**Comment by dezoxel** [comment]
Done. @Kostya47 regression needed, please test

**Comment by Kostya47** [comment]
![test run 7_28_2016 - testrail-1](https://cloud.githubusercontent.com/assets/18617219/17216819/dae5f0e0-54ea-11e6-9d35-4ae0e66efd74.png)

**NOTE:** T41 not worked before. Closed.
