### ISSUE TITLE
Show current week when Sunday

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#45]
Now we have a such logic:
- When the last day in current week comes, we get this message:
  ![- google chrome_001](https://cloud.githubusercontent.com/assets/18617219/17204960/26b29c6a-54b1-11e6-9143-0a632e5f39dd.png)
- It still remains in such view before Monday, then displays the current menu with the order already from Tuesday.

I think it would be more correct, when on Sunday (or even Saturday) will be displayed order for next week. For users not really matter what was on the menu last week, but make order for next week will be easier.

**Comment by dezoxel** [comment]
Good point, will implement soon

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
