### ISSUE TITLE
Implement user model

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#52]
``` js
export interface IUser {
  id: number;
  fullName: string;
  role: number;
  address?: string;
}

export enum Role {
  Guest,
  Customer
}
```
- Store user in local storage
- If no user in local storage - create guest and store
- Sync user with API

**Comment by dezoxel** [comment]
Done. @Kostya47 regression testing needed

**Comment by Kostya47** [comment]
Tested.
![test run 7-29-2016 - testrail - google chrome_005](https://cloud.githubusercontent.com/assets/18617219/17251978/79fedc8c-55b3-11e6-9ff1-f466aaffba30.png)
