### ISSUE TITLE
Favicon needed

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#56]

**Comment by dezoxel** [comment]
@Kostya47 please find appropriate free icon. When found - assign to me

**Comment by Kostya47** [comment]
Here are the icons that I has looked:
![catering-favicon](https://cloud.githubusercontent.com/assets/18617219/17359903/76ef1cca-5971-11e6-8197-947cbb7049d9.png)
![favicon-cultural-food](https://cloud.githubusercontent.com/assets/18617219/17359904/76ef5a82-5971-11e6-997a-0b823fb9618d.png)
![favicon-01](https://cloud.githubusercontent.com/assets/18617219/17359905/76f41e5a-5971-11e6-8b7b-9100ec60c3c4.png)
![restaurant-food-icon-16](https://cloud.githubusercontent.com/assets/18617219/17359906/76f6754c-5971-11e6-93fc-6da56e2f1253.png)
![vkeong com](https://cloud.githubusercontent.com/assets/18617219/17359952/ac1b8e56-5971-11e6-8b39-7ad6dbee1a21.png)

Last seems to me the optimal.

**Comment by dezoxel** [comment]
Done, @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
