### ISSUE TITLE
Strange display of price

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#6]
В меню на любой день, если снять флажки со всех продуктов, то цена рядом будет отображена как "0 грн"

Мне кажется, в таком случае лучше совсем не отображать цену.

**Comment by warlock39** [comment]
I recommend to display custom "call to action" when user reaches this case. For example phrase: "Choose dishes before, and we will calculate sum of products that you have checked".

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified
