### ISSUE TITLE
Need to improve actions after clicking on the add to basket button

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#7]
Я к примеру беру меню на один из дней, настраиваю всё что мне нужно выбирая размер порции и количество, после чего жму на кнопку "Беру" и тут же всё меню на этот день слетает на вид по умолчанию. Нужно либо как-то нагляднее сделать, что это ушло в корзину или не возвращать в состояние "по умолчанию"

**Comment by dezoxel** [comment]
Fixed. @Kostya47 please test

**Comment by Kostya47** [comment]
@dezoxel please add some rectification.

**For example:**
Instead "Line items were added to basket. Want more?"

Can be "Line items were added to basket. Want more for Monday? "

**Comment by dezoxel** [comment]
@Kostya47 Can you please provide full list of requirements for this particular case?

**Comment by Kostya47** [comment]
@dezoxel You have already fixed it. Everything looks clear. 
Closed.
