### ISSUE TITLE
Doesn't store customer name in local storage after placing order

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#73]
**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any products.
3. Go to basket.
4. Fill name and address.
5. Press place order.
6. Go to my-orders.

**AR:** "No orders for a selected period of time"
**ER:** Must display your placed orders.

**Comment by dezoxel** [comment]
@Kostya47 duplicate of https://github.com/lunches-platform/fe/issues/54. Please test

**Comment by Kostya47** [comment]
It's not a duplicate. Close when fix https://github.com/lunches-platform/fe/issues/96

**Comment by Kostya47** [comment]
Closed.
