### ISSUE TITLE
Нажатие кнопки "Беру" при снятых чекбоксах

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#8]
Если снять все флажки в меню на одном из дней и нажать на кнопку "Беру", происходит сброс до вида по умолчанию.

Кнопка "Беру" не должна быть активна.

**Comment by dezoxel** [comment]
@Kostya47 it was fixed as a part of https://github.com/lunches-platform/fe/issues/6. Please test

**Comment by Kostya47** [comment]
Verified
