### ISSUE TITLE
[Week Menu] Replace dishes list with the md-list instead of plain text

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/fe#84]
Problem: it is not enough clear what is the lunch contents because dish list is plain text.
Solution: We have to concentrate user's attention on the dish list. It is possible to achieve using md-list with icons

Requirements:
- md-list
- Three icons: salad, garnish, meat (fish)

Notes:
- Prefered icons are in material design style

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
