### ISSUE TITLE
Don't hide passed days on week menu page

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#9]
Case description:
For now Thursday 7 of July, I want to order something and go to `http://cogniance.lunches.com.ua/`. I see full weekly menu including dates in the past (Mon 4th, Tue 5th, Wed 6th and Thu 7th) - it's wrong and misleading. Will be more correctly that these days are not displayed.

**Comment by warlock39** [comment]
But it is required to look full weekly menu by clicking on appropriate button.

**Comment by dezoxel** [comment]
Fixed, @Kostya47 please test

**Comment by Kostya47** [comment]
@dezoxel 
Now is 11 of July and I see menu for today. Is this correct work?
![fountainjs - google chrome_001](https://cloud.githubusercontent.com/assets/18617219/16735506/f175fe24-4791-11e6-924a-fdb11fe072eb.png)

**Comment by dezoxel** [comment]
Nope, will fix it later.

**Comment by dezoxel** [comment]
@Kostya47 ahh, sorry, I forgot to deploy my code. It is fixed already. Please test again

**Comment by Kostya47** [comment]
Verified.
