### ISSUE TITLE
"Name" field filled by default

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#95]
**Preconditions:**
Local storage data must be cleaned.

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.

**AR:** 
![- google chrome_008](https://cloud.githubusercontent.com/assets/18617219/17393157/91cd24ba-5a2a-11e6-84c3-7f35b2ea33cb.png)

**ER:** "Name" field must be empty by default.

**Comment by dezoxel** [comment]
Done. @Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
