### ISSUE TITLE
Stores the old data in "Address" field

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#96]
**Preconditions:**
Local storage data must be cleaned.

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.
4. Fill name (example: Test User One).
5. Fill address (example: 1).
6. Place order.
7. Again add any product.
8. Go to basket.
9. Fill name (example: Test User Two).
10. Fill address (example: 2).
11. Place order.
12. And again add any product.
13. Go to basket.

**AR:**
![- google chrome_009](https://cloud.githubusercontent.com/assets/18617219/17393803/9511a624-5a2e-11e6-86eb-b0b7b880729d.png)
**ER:** Address field must contain the number 2.

**Comment by dezoxel** [comment]
Fixed as a part of https://github.com/lunches-platform/fe/issues/77

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
@dezoxel Issue is still present.

**Comment by Kostya47** [comment]
Already fixed. Closed.
