### ISSUE TITLE
Non active "Place order" button while the required fields are filled

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#97]
**Preconditions:**
Name and address should be in local storage.

**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Add any product.
3. Go to basket.

**AR:** "Place order" button is inactive.
**ER:** Button must be active.

**Note:** I guess the problem is because of this: `"customer": null, "address": null,`. Data remains in this form until edit address field and change focus to name field.

**Comment by dezoxel** [comment]
Fixed as a part of https://github.com/lunches-platform/fe/issues/77

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified.
